# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: development
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: production
  username: postgres
  password: postgres
